# This is a basic workflow to help you get started with Actions

name: X-UI Release

# Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * 1,5"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: GoLang 1.x.y
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.3' # The Go version to download (if necessary) and use.
      - name: Start Setup
        run: |
          sudo apt-get update
          sudo apt-get install -yq git sshpass gcc-aarch64-linux-gnu gcc-s390x-linux-gnu gcc-riscv64-linux-gnu python-is-python3
          curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > $HOME/repo
          sudo mv $HOME/repo /usr/bin/
          sudo chmod +x /usr/bin/repo
      - name: Setup git Store Password
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global credential.helper store
          export FULL_TOKEN=${{ secrets.TOKEN_ONE }}${{ secrets.TOKEN_TWO }}${{ secrets.TOKEN_THREE }}
          sshpass -p ${FULL_TOKEN} git clone https://dopaemon@github.com/X-UI-Unofficial/Store-Passwd.git
      - name: Start repo Source
        run: |
          mkdir -p $HOME/X-UI
          cd $HOME/X-UI
          repo init -u https://github.com/X-UI-Unofficial/manifest.git -b main
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - name: Start Building X-UI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -rf $HOME/X-UI/x-ui/web/translation/.git
          rm -rf $HOME/X-UI/x-ui/bin/.git
          rm -rf $HOME/X-UI/x-ui/web/.git
          rm -rf $HOME/X-UI/x-ui/web/translation/.placeholder
          rm -rf $HOME/X-UI/x-ui/bin/.placeholder
          rm -rf $HOME/X-UI/x-ui/web/.placeholder
          cd $HOME/X-UI/x-ui/
          ./build
